// Code generated by protoc-gen-go-grpc-mock. DO NOT EDIT.
// source: petstore.proto

package petstore

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockPetStoreClient is a mock of PetStoreClient interface.
type MockPetStoreClient struct {
	ctrl     *gomock.Controller
	recorder *MockPetStoreClientMockRecorder
}

// MockPetStoreClientMockRecorder is the mock recorder for MockPetStoreClient.
type MockPetStoreClientMockRecorder struct {
	mock *MockPetStoreClient
}

// NewMockPetStoreClient creates a new mock instance.
func NewMockPetStoreClient(ctrl *gomock.Controller) *MockPetStoreClient {
	mock := &MockPetStoreClient{ctrl: ctrl}
	mock.recorder = &MockPetStoreClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPetStoreClient) EXPECT() *MockPetStoreClientMockRecorder {
	return m.recorder
}

// CreatePet mocks base method.
func (m *MockPetStoreClient) CreatePet(ctx context.Context, in *Pet, opts ...grpc.CallOption) (*Pet, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreatePet", varargs...)
	ret0, _ := ret[0].(*Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePet indicates an expected call of CreatePet.
func (mr *MockPetStoreClientMockRecorder) CreatePet(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePet", reflect.TypeOf((*MockPetStoreClient)(nil).CreatePet), varargs...)
}

// DeletePet mocks base method.
func (m *MockPetStoreClient) DeletePet(ctx context.Context, in *Pet, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeletePet", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePet indicates an expected call of DeletePet.
func (mr *MockPetStoreClientMockRecorder) DeletePet(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePet", reflect.TypeOf((*MockPetStoreClient)(nil).DeletePet), varargs...)
}

// GetAll mocks base method.
func (m *MockPetStoreClient) GetAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Pets, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].(*Pets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPetStoreClientMockRecorder) GetAll(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPetStoreClient)(nil).GetAll), varargs...)
}

// GetPet mocks base method.
func (m *MockPetStoreClient) GetPet(ctx context.Context, in *Pet, opts ...grpc.CallOption) (*Pet, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPet", varargs...)
	ret0, _ := ret[0].(*Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPet indicates an expected call of GetPet.
func (mr *MockPetStoreClientMockRecorder) GetPet(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPet", reflect.TypeOf((*MockPetStoreClient)(nil).GetPet), varargs...)
}

// UpdatePet mocks base method.
func (m *MockPetStoreClient) UpdatePet(ctx context.Context, in *Pet, opts ...grpc.CallOption) (*Pet, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdatePet", varargs...)
	ret0, _ := ret[0].(*Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePet indicates an expected call of UpdatePet.
func (mr *MockPetStoreClientMockRecorder) UpdatePet(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePet", reflect.TypeOf((*MockPetStoreClient)(nil).UpdatePet), varargs...)
}

// MockPetStoreServer is a mock of PetStoreServer interface.
type MockPetStoreServer struct {
	ctrl     *gomock.Controller
	recorder *MockPetStoreServerMockRecorder
}

// MockPetStoreServerMockRecorder is the mock recorder for MockPetStoreServer.
type MockPetStoreServerMockRecorder struct {
	mock *MockPetStoreServer
}

// NewMockPetStoreServer creates a new mock instance.
func NewMockPetStoreServer(ctrl *gomock.Controller) *MockPetStoreServer {
	mock := &MockPetStoreServer{ctrl: ctrl}
	mock.recorder = &MockPetStoreServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPetStoreServer) EXPECT() *MockPetStoreServerMockRecorder {
	return m.recorder
}

// CreatePet mocks base method.
func (m *MockPetStoreServer) CreatePet(ctx context.Context, in *Pet) (*Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePet", ctx, in)
	ret0, _ := ret[0].(*Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePet indicates an expected call of CreatePet.
func (mr *MockPetStoreServerMockRecorder) CreatePet(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePet", reflect.TypeOf((*MockPetStoreServer)(nil).CreatePet), ctx, in)
}

// DeletePet mocks base method.
func (m *MockPetStoreServer) DeletePet(ctx context.Context, in *Pet) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePet", ctx, in)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePet indicates an expected call of DeletePet.
func (mr *MockPetStoreServerMockRecorder) DeletePet(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePet", reflect.TypeOf((*MockPetStoreServer)(nil).DeletePet), ctx, in)
}

// GetAll mocks base method.
func (m *MockPetStoreServer) GetAll(ctx context.Context, in *emptypb.Empty) (*Pets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, in)
	ret0, _ := ret[0].(*Pets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPetStoreServerMockRecorder) GetAll(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPetStoreServer)(nil).GetAll), ctx, in)
}

// GetPet mocks base method.
func (m *MockPetStoreServer) GetPet(ctx context.Context, in *Pet) (*Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPet", ctx, in)
	ret0, _ := ret[0].(*Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPet indicates an expected call of GetPet.
func (mr *MockPetStoreServerMockRecorder) GetPet(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPet", reflect.TypeOf((*MockPetStoreServer)(nil).GetPet), ctx, in)
}

// UpdatePet mocks base method.
func (m *MockPetStoreServer) UpdatePet(ctx context.Context, in *Pet) (*Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePet", ctx, in)
	ret0, _ := ret[0].(*Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePet indicates an expected call of UpdatePet.
func (mr *MockPetStoreServerMockRecorder) UpdatePet(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePet", reflect.TypeOf((*MockPetStoreServer)(nil).UpdatePet), ctx, in)
}
